allotools_user:
    resource: "@AllotoolsUserBundle/Resources/config/routing.yml"
    prefix:   /

allotools_faq:
    resource: "@AllotoolsFaqBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@AllotoolsUserBundle/Resources/config/routing/security.yml"

fos_user_profile:
    resource: "@AllotoolsUserBundle/Resources/config/routing/profile.yml"
    prefix: /compte

fos_user_register:
    resource: "@AllotoolsUserBundle/Resources/config/routing/registration.yml"
    prefix: /inscription

fos_user_resetting:
    resource: "@AllotoolsUserBundle/Resources/config/routing/resetting.yml"
    prefix: /resetting

fos_user_change_password:
    resource: "@AllotoolsUserBundle/Resources/config/routing/change_password.yml"
    prefix: /compte

