imports:
    - { resource: "@AllotoolsUserBundle/Resources/config/security.yml" }
security:

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }


    role_hierarchy:
        ROLE_CLI: ROLE_CLI
        ROLE_ADMIN: ROLE_ADMIN
