<?php

namespace Allotools\FaqBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArbreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArbreRepository extends EntityRepository
{
//WHERE p.id = :id
//AND c.public = true
//AND a.actif = true
    public function getTop5AllowedArbres($id)
    {
        if ($id != null)
            return $this->getEntityManager("customer")
                ->createQuery(
                    'SELECT a
                     FROM AllotoolsFaqBundle:Arbre a
                     JOIN a.categorie c
                     JOIN c.profil p
                     WHERE (p.id = :id OR c.public = true)
                     AND a.actif = true
                     ORDER BY a.nb_vue DESC'
                )->setMaxResults(5)->setParameter('id', $id)->getResult();
        else
            return $this->getEntityManager("customer")
                ->createQuery(
                    'SELECT a
                     FROM AllotoolsFaqBundle:Arbre a
                     JOIN a.categorie c
                     WHERE c.public = true
                     AND a.actif = true
                     ORDER BY a.nb_vue DESC'
                )->setMaxResults(5)->getResult();
    }

    public function findAllOByLib($lib, $id)
    {
        if ($id != null)
            return $this->getEntityManager("customer")
                ->createQuery(
                    'SELECT a
                     FROM AllotoolsFaqBundle:Arbre a
                     JOIN a.categorie c
                     JOIN c.profil p
                     WHERE a.libelle LIKE :lib
                     AND (c.public = true OR p.id = :id)
                     AND a.actif = true'
                )->setParameter('lib', '%' . $lib . '%')->setParameter('id', $id)->getResult();
        else
            return $this->getEntityManager("customer")
                ->createQuery(
                    'SELECT a
                     FROM AllotoolsFaqBundle:Arbre a
                     JOIN a.categorie c
                     WHERE a.libelle LIKE :lib
                     AND c.public = true
                     AND a.actif = true'
                )->setParameter('lib', '%' . $lib . '%')->getResult();
    }


    public function findArbreJoinCategorieJoinProfil($id)
    {
        $query = $this->getEntityManager($id)
            ->createQuery('
            SELECT a FROM AllotoolsFaqBundle:Arbre a
            JOIN a.categorie c
            JOIN c.profil p
            WHERE p.id = :id
            AND a.actif = true'
            )->setParameter('id', $id);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
