<?php

namespace Allotools\FaqBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findAllowedArticles($profilID, $keyword)
    {

        if ($profilID == null)
            return $this->getEntityManager("customer")
                ->createQuery(
                    'SELECT a
                     FROM AllotoolsFaqBundle:Article a
                     JOIN a.categories c
                     WHERE c.public = true
                     AND a.keywords LIKE :keyword
                     AND a.actif = 1'
                )->setParameter('keyword', "%" . $keyword . "%")->getResult();
        else
            return $this->getEntityManager("customer")
                ->createQuery(
                    'SELECT a
                     FROM AllotoolsFaqBundle:Article a
                     JOIN a.categories c
                     JOIN c.profil p
                     WHERE (p.id = :id
                     OR c.public = true)
                     AND a.keywords LIKE :keyword
                     AND a.actif = 1'
                )->setParameter('id', $profilID)->setParameter('keyword', "%" . $keyword . "%")->getResult();
    }

    public function getAllowedArticlesContent($profilID, $id)
    {

        if ($profilID != null)
            return $this->getEntityManager("customer")
                ->createQuery(
                    'SELECT a
                     FROM AllotoolsFaqBundle:Article a
                     JOIN a.categories c
                     JOIN c.profil p
                     WHERE (p.id = :id
                     OR c.public = true)
                     AND a.id = :idArt
                     AND a.actif = true'
                )->setParameter('id', $profilID)->setParameter('idArt', $id)->getResult();
        else
            return $this->getEntityManager("customer")
                ->createQuery(
                    'SELECT a
                     FROM AllotoolsFaqBundle:Article a
                     JOIN a.categories c
                     WHERE c.public = true
                     AND a.id = :idArt
                     AND a.actif = true'
                )->setParameter('idArt', $id)->getResult();
    }

    public function getArticles($route)
    {
        return $this->getEntityManager("customer")
            ->createQuery('
                                SELECT a
                                FROM AllotoolsFaqBundle:Article a
                                JOIN a.categories c
                                WHERE c.route = :route
                                AND a.actif = true')
            ->setParameter('route', $route)->getResult();

    }

    public function getArticlesLibelle($route, $libelle)
    {
        return $this->getEntityManager("customer")
            ->createQuery('
                                SELECT a
                                FROM AllotoolsFaqBundle:Article a
                                JOIN a.categories c
                                WHERE c.route = :route
                                AND a.titre LIKE :libelle
                                ')
            ->setParameter('route', $route)->setParameter('libelle', "%" . $libelle . "%")->getResult();

    }


}
