<?php

namespace Allotools\FaqBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleUtileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleUtileRepository extends EntityRepository
{

    public function findarticleutilesByDateCateg($route){
        return $this->getEntityManager("customer")
            ->createQuery('
                                SELECT au
                                FROM AllotoolsFaqBundle:ArticleUtile au
                                JOIN au.article a
                                JOIN a.categories c
                                WHERE c.route = :route')


            ->setParameter('route', $route)->getResult();

    }

    public function getArticleUtilePourArticle($idArticle){
        return $this->getEntityManager("customer")
            ->createQuery('
                                SELECT au
                                FROM AllotoolsFaqBundle:ArticleUtile au
                                JOIN au.article a
                                JOIN a.categories c
                                WHERE a.id = :id')


            ->setParameter('id', $idArticle)->getResult();

    }


        public function findarticleVusByCateg($route, $id){
            return $this->getEntityManager("customer")
                ->createQuery('
                                SELECT au
                                FROM AllotoolsFaqBundle:ArticleUtile au
                                JOIN au.article a
                                JOIN a.categories c
                                WHERE c.route = :route
                                AND au.utile=:id')

                ->setParameter('route', $route)->setParameter('id', $id)->getResult();

        }



}
