<?php

namespace Allotools\FaqBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
        public function findAllowedCategories($profilID, $keyword){
                if($profilID != null)
                        return $this->getEntityManager("customer")
                        ->createQuery(
                        'SELECT c
                         FROM AllotoolsFaqBundle:Categorie c
                         JOIN c.profil p
                         WHERE c.lib LIKE :lib
                         AND (c.public = true OR p.id = :id)'
                        )->setParameter('id', $profilID)->setParameter('lib',"%".$keyword."%")->getResult();
                else
                        return $this->getEntityManager("customer")
                                ->createQuery(
                                        'SELECT c
                                         FROM AllotoolsFaqBundle:Categorie c
                                         WHERE c.public = true
                                         AND c.lib LIKE :lib'
                                )->setParameter('lib',"%".$keyword."%")->getResult();


        }

        public function getAllowedArticlesContent($profilID, $route){

                if($profilID != null)
                        return $this->getEntityManager("customer")
                                ->createQuery(
                                        'SELECT a
                                         FROM AllotoolsFaqBundle:Article a
                                         JOIN a.categories c
                                         JOIN c.profil p
                                         WHERE c.route LIKE :route
                                         AND a.actif = true
                                         AND (c.public = true OR p.id = :id)'
                                )->setParameter('id', $profilID)->setParameter('route',"%".$route."%")->getResult();
                else
                        return $this->getEntityManager("customer")
                                ->createQuery(
                                        'SELECT a
                                         FROM AllotoolsFaqBundle:Article a
                                         JOIN a.categories c
                                         WHERE c.public = true
                                         AND c.route LIKE :route
                                         AND a.actif = true'
                                )->setParameter('route',"%".$route."%")->getResult();
        }

        public function getCategorieLibelle($libelle){
            return $this->getEntityManager("customer")
                ->createQuery('
                                    SELECT c
                                    FROM AllotoolsFaqBundle:Categorie c
                                    WHERE c.lib like :libelle

                                    ')
                ->setParameter('libelle',"%".$libelle."%")->getResult();

        }
}
